// src/components/TaskBar/TrayClock.tsx
import moment from "moment";
import {useEffect, useState} from "react";

const timeFormat = 'YYYY/MM/DD ddd HH:mm:ss'
export default function () {
  const [time, setTime] = useState(moment().format(timeFormat))

  useEffect(() => {
    const interval = setInterval(() => {
      setTime(moment().format(timeFormat))
    })

    return () => clearInterval(interval)
  }, []);

  return <div className="tray-datetime">{time}</div>
}

// frontend/src/components/OS/TaskBar/TrayClock.vue
<script lang="ts">
import {defineComponent} from 'vue'
import moment from 'moment'

const timeFormat = 'HH:mm:ss<br>ddd YYYY/MM/DD'

export default defineComponent({
  name: 'TrayClock',
  setup() {
    const time = ref('')
    const intervalRef = ref()

    onMounted(() => {
      intervalRef.value = setInterval(() => {
        time.value = moment().format(timeFormat)
      })
    })

    onBeforeUnmount(() => {
      clearInterval(intervalRef.value)
    })
    return {
      time,
    }
  },
})
</script>

<template>
  <div class="tray-datetime" v-html="time"></div>
</template>

<style lang="scss" scoped>
.tray-datetime {
  padding: 2px 4px;
  text-align: right;
  font-size: 10px;
  line-height: 1.5;
}
</style>
